apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: ${parameters.replicas}
  template:
    spec:
      containers:
        - name: nginx
          image: ${parameters.image}
          resources:
            requests:
              cpu: ${parameters.cpu}
              memory: ${parameters.memory}
